### ISSUE TITLE
Index I spec

### ISSUE THREAD

**Issue by diatomsRcool** [helxplatform/dbgaptools#3]
Create the specification for Index I. We need this to know how the data dictionary parser will output data.
Blocked by #2

**Comment by diatomsRcool** [comment]
In addition to what NLP needs add:
variable full accession number
data set full accession number
study full accession number

**Comment by diatomsRcool** [comment]
From @bheavner variable name, encoded values (categorical variable meanings e.g. 1 = Male, 2 = Female), data set description (perhaps a link to that?), study descriptions, variable ID (phv*) and version, data set id (pht*) and version, and study accession (phs*) and version. Study accession may not be in data dictionary, but possible to build with parsing tool.

**Comment by diatomsRcool** [comment]
In Index I, every row will be a variable. The columns are specified below. Index I will be tab-delimited and will have a header row.
*Index I specification*:
variable name (text string) required
encoded values (categorical variable meanings e.g. 1 = Male, 2 = Female) optional
data set description (text) optional
study description (text) optional
variable full accession number (alphanumeric) required
data set full accession number (alphanumeric) required
study full accession number (alphanumeric) required
variable unit (string) optional
@bheavner does the "full accession number" include the version number and consent group?

**Comment by diatomsRcool** [comment]
@kwuichet @stevencox @bheavner 
What do you think about the proposed specification for Index I above?

**Comment by bheavner** [comment]
I like this, but want to talk with @amstilp to see if that will be sufficient for search. I think this will be a high-priority discussion point for the WG in the near future.

**Comment by bheavner** [comment]
need to address #6 in this format, too

**Comment by bheavner** [comment]
A couple considerations come to mind: data set description may be long text; study description may be long text; it gets complicated when you index the encoded values, since there can be multiple encoded values for a single variable. You can't easily put that in a csv file - perhaps a JSON (JSON-LD?) format would be better? I don't really know much about indexing/search code, so don't know how complicated the index data structure can be. csv may be too simple for our needs.

**Comment by diatomsRcool** [comment]
The long text doesn't worry me so much. I think we can put the encoded values in a csv file and use a pipe delimiter to separate them or some such. It's doable, but JSON may be better. @stevencox @alexwaldrop @deepakunni3 Any opinions?
Male=0|Female=1
vs
'encoded_values':{'Male':'0', 'Female':'1'}

**Comment by stevencox** [comment]
JSON's probably best. Libraries for handling it are pervasive and the pitfalls of CSV numerous.

**Comment by diatomsRcool** [comment]
From Deepak - JSON is better
From Howard - JSON is better

**Comment by diatomsRcool** [comment]
Ben - maybe add a link to a landing page with more info about the variable.

**Comment by bheavner** [comment]
Example dbGaP landing page: [https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/variable.cgi?study_id=phs000007.v30.p11&phv=159482&phd=4398&pha=4313&pht=3099&phvf=&phdf=&phaf=&phtf=&dssp=1&consent=&temp=1](https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/variable.cgi?study_id=phs000007.v30.p11&phv=159482&phd=4398&pha=4313&pht=3099&phvf=&phdf=&phaf=&phtf=&dssp=1&consent=&temp=1)

**Comment by diatomsRcool** [comment]
@bheavner if you are happy with the output files, please close this issue

**Comment by bheavner** [comment]
Thanks. I've asked Adrienne to look at an output file to give her input.

**Comment by bheavner** [comment]
Some feedback:

for VARIABLE_ACC, DATASET_ACC, STUDY_ACC, they probably should store the phv/pht/phs separately from the version. Instead of this:
        "VARIABLE_ACC": "phv00252976.v1",
        "DATASET_ACC": "pht005002.v1",
        "STUDY_ACC": "phs000956.v3",
maybe this:
        "VARIABLE_ACC": "phv00252976",
        "VARIABLE_VERSION": "v1",       
        "DATASET_ACC": "pht005002",
        "DATASET_VERSION": "v1",
        "STUDY_ACC": "phs000956",
        "STUDY_VERSION": "v3",
Reasoning: If a new version of a variable is available in a new version of the study, they'll want to be able to identify it as an updated version. This is harder if they keep it as "phv00252976.v1".
I'm also not sure if they should store the integer (e.g., 252976) or the string (e.g., "phv00252976").
Same with versions, the integer (1) vs the string ("v1").

The variable type (possibly useful, depending on what they want to do with the data) and date created (probably less useful) are missing.
variable type is not guaranteed to be correct. We store the variable type specified in the data dictionary but also the variable type that we've detected the data values to have.

**Comment by amstilp** [comment]
Another useful field to add is the dataset name. Unfortunately, the dataset name is not in the XML file, but it is part of the filename and can be parsed with a regex. For example, the dataset name for this file:
`phs000956.v3.pht005002.v1.TOPMed_WGS_Amish_Subject_Phenotypes.data_dict.xml`
is "TOPMed_WGS_Amish_Subject_Phenotypes".

**Comment by alexwaldrop** [comment]
@amstilp @bheavner Update on the parser. Just pushed a commit that incorporate both of the changes you suggested into the parser. To recap, VARIABLE_ACC, DATASET_ACC, STUDY_ACC now hold the raw ids (as strings to prevent truncating the leading 0s) parsed from the original id string. VARIABLE_VERSION, DATASET_VERSION, and STUDY_VERSION now hold the version ids also parsed from the original id string. 

Just a heads up, the parser now checks the format of all three id variables against a regex and will raise an error and exit if any ids don't match the correct form. If we want this to be a warning only I can modify. 

Also, parser now grab study name from the filename if the filename matches the correct regex. As this isn't a required field and to keep things flexible, it will just set the study name to NULL if one can't be parsed from the filename.

Sample output for file: phs000001.v1.pht000001.v1.ardpheno.data_dict_2008_10_31.xml

    {
        "VARIABLE_ACC": "00000027",
        "VARIABLE_VERSION": "1",
        "DATASET_ACC": "000001",
        "DATASET_VERSION": "1",
        "DATASET_PARTICIPANT_SET": "1",
        "STUDY_ACC": "000001",
        "STUDY_VERSION": "1",
        "STUDY_NAME": "ardpheno",
        "DATASET_DESC": null,
        "VARNAME": "agephot",
        "VARDESC": "Age at last photograph",
        "UNITS": "year",
        "ENCODED_VALUES": null
    },

All changes are pushed and now live on Docker as well under the 'latest' tag. Let me know if we can think of other things.

**Comment by amstilp** [comment]
Looks better, except that "study_name" should be "dataset_name". There can be multiple datasets per study, and they each have their own names. Also, "dataset_participant_set" should probably be renamed to "study_participant_set" if you want to track it. There is one participant set for each study version, and every dataset from that study gets that participant set number attached. See this paper for more info, in particular the "dbGaP accessioned objects" section: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2031016/
I don't think it says clearly in this paper that the participant set number increases when subjects change or withdraw consent, but not when new subjects are added.

**Comment by diatomsRcool** [comment]
maybe data set name and study name?

**Comment by alexwaldrop** [comment]
@amstilp @diatomsRcool Got it. I'll make these updates today changing "study_name" to "dataset_name" and "dataset_participant_set" to "study_participant_set"

**Comment by diatomsRcool** [comment]
@alexwaldrop was this update done?

**Comment by alexwaldrop** [comment]
@diatomsRcool Sorry for delay. I'll have by end of today or tomorrow at the latest.

**Comment by alexwaldrop** [comment]
@diatomsRcool Got the new column headers updated and committed. Also pushed to Docker latest so changes are now live.

**Comment by diatomsRcool** [comment]
Excellenty! I'm going to close this issue. If any other problems come up we can start a new one.
