### ISSUE TITLE
Docker install failed

### ISSUE THREAD

**Issue by bheavner** [helxplatform/dbgaptools#7]
Attempting to test install following [readme instructions](https://github.com/heliumplusdatastage/dbgaptools/blob/development/python/README.md) in dev branch:

```
docker pull heliumdatastage/dbgap_dd_to_json:latest
Error response from daemon: manifest for heliumdatastage/dbgap_dd_to_json:latest not found
```

**Comment by alexwaldrop** [comment]
@bheavner the actual latest tag is heliumdatastage/dbgap_dd_to_json:b4ca527, but didn't want to put that in the documentation as this will change over time. I can create an image with the 'latest' tag, but we may want to consider sticking with a static tag as the 'latest' image could change over time and still have the same tag. What are your thoughts?

**Comment by bheavner** [comment]
Hrm. I don't have much experience with it, but from Google, it sounds like people have strong opinions about the latest tag (e.g. https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375 ).  Perhaps a version? I'm not sure how to best resolve the fact that the instructions don't work at the moment. Remembering to update the README when containerizing seems like a pain, but perhaps it's necessary?

**Comment by deepakunni3** [comment]
@alexwaldrop I would recommend using `latest` tag since the tool is still in development.
Once it moves to production, you can tag it to a stable version - which is what a production environment will be using. This still leaves `latest` to be the bleeding edge (with the understanding that things might be unstable with this tag).

**Comment by alexwaldrop** [comment]
@deepakunni3 I agree using the latest tag may be easiest during development. @bheavner just pushed a copy of the image with the latest tag to DockerHub so it should work now.

**Comment by bheavner** [comment]
```
bheavner$ docker pull heliumdatastage/dbgap_dd_to_json
Using default tag: latest
latest: Pulling from heliumdatastage/dbgap_dd_to_json
27833a3ba0a5: Pull complete 
ad5023f26108: Pull complete 
35d55d99e929: Pull complete 
c73ae40fc363: Pull complete 
35b7d6938a3d: Pull complete 
dcca4889dc3c: Pull complete 
eb3a3dde0b00: Extracting  63.85MB/63.85MB
fa811d209cc1: Download complete 
c8ae8a7087be: Download complete 
35144e9a73c3: Download complete 
656a50d6fe82: Download complete 
2514811f1002: Download complete 
33ec50278720: Download complete 
1c609c37bdec: Download complete 
a07515902a35: Download complete 
1a737789e661: Download complete 
1d29bfd89bae: Download complete 
2e25e2c08a28: Download complete 
```
